### ISSUE TITLE
Problem iommi aims to solve?

### ISSUE THREAD

**Issue by casoetan** [TriOptima/iommi#41]
Hi guys,

This looks good, but I'm missing the reason / problem this solves.

Is it replacing the default Django admin?

**Comment by boxed** [comment]
It replaces django forms, and introduces a table abstraction and a db filtering abstraction. Then it also supplies higher level constructs based on that, and on top of THAT in turn it supplies an admin to replace the django admin. And there are other parts too like Action, Menu, Page. 

It's a toolkit to make traditional web pages (as opposed to SPAs).

But the admin part is probably quite annoying to use right now as it's rather new. It is more configurable than djangos admin though, and if you want to take the work you've spent customizing one page outside the admin that is trivial. You don't get the situation you get with the django admin that when you've hit the limits you have to start from scratch.

**Comment by jpic** [comment]
The problem is pretty obvious: Django admin provides barely anything that's usable for non-admin, not even working base templates and sane default features such as searchable lists with some kind of row level security, and only basic HTML forms without even a default template that calls `{{ form }}` and `{{ form.media }}` and `{% csrf_token %}`. 

For example, Django would need to have a base.html that can display a `View.title` attribute, exactly like in all CMS and frameworks that exist on top of Django, and that Iommi solves with a *beautiful python API for generating HTML*. Personnally I'd be better off without templates at all, so ultimately I would like to reach the level where this is possible:

```python
class IommiView:
    template = BaseTemplate(
        title='Your Title',
        content=[
            ... list of python components here
            ... and name of methods too
        ]
    )
```

Obviously, I believe all 1337 h4x0|2z will agree on eliminating templates, not even for being slower than pure python, but just to move on to Decorator based patterns for generating some tag-based HTML source code, just like we would for any GUI according to the GoF on Decorator patterns. Anyway, all your CRUD code would be MUCH better with a Controller layer, that sits between a model and it's set of CRUD views to form the MVC that makes modifying the admin so pleasant. Take this example of registering a full CRUD with the MVC pattern just like the Admin:

```python
crudlfap.Controller(
    Artist,
    fields='__all__',
).register()
```

This must enable a working CRUD view that is **superuser only** by default. You override your Controller.get_queryset which all of the views will call so that it is **secure by default** (which default CBV **are not**), overriding the Controller is a lot of fun just like in the admin because it is the result of a standard **refactor of the code in-between Models and Views**:

```python
class UserController(crudlfap.Controller):
    views = [
        # some view defined above in crud.py:
        ImportView,  
        # a working from imported from mvc.auth
        PasswordResetView,
        UserUpdateView,
        UserCreateView,
        # same but overriding a view kwarg
        BecomeUser.clone(
            allowed_groups=['Admin'],
        ),
        # with default template with fields/exclude on DetailView
        crudlfap.DetailView.clone(
            exclude=[
                'password',
                'permissions',
            ]
        ),
        UserListView,
    ]
    allowed_groups = ['Admin', 'Superviseur']
    material_icon = 'person'
    model = User
    urlfield = 'pk'


    # You want all your views to get the base queryset from the controller
    # wich is awesome it centralize your crud
    # queryset filtering for permissions

    def get_queryset(self, view):
        user = view.request.user

        if user.profile == 'admin':
            return self.model.objects.all()
        elif user.profile == 'superviseur':
            return self.model.objects.filter(
                caisses__in=view.request.user.caisses.all()
            ).exclude(
                groups__name__in=('Superviseur', 'Admin')
            ).distinct()

        # STILL secure by default
        return self.model.objects.none()

# Easier register() call
UserController().register()
```


But you will reach your full potential when you can add your own `ObjectFormView` with custom allowance based on properties of the object, ie: can't validate a model instance with status='accepted'

```
class MRSRequestRejectView(EmailViewMixin,
                           MRSRequestStatusMixin,
                           crudlfap.ObjectFormView):

    # Show in detail view only, this would be menus = ['object_row', 'object_detail'] by default
    menus = ['object_detail']  # show reject menuitem for object menu of the detail page only !

    
    view_label = 'Rejeter'  # should be "reject" by default
    material_icon = 'do_not_disturb_on' # used in menu
    color = 'red' # used for menu item color
    action_flag = MRSRequest.STATUS_REJECTED # for the mrsstatus mixin
    
    # this puts data-modal="bottom" in the link, 
    # causing links to this view to spawn in a modal,
    # note that they also work from outside modals: directly with the url
    link_attributes = BOTTOM_MODAL
    
    # this will secure the view from being used against arbitrary objects
    # STILL call super().get_queryset() to get a secure queryset from the controller
    def get_queryset(self):
        return super().get_queryset().filter(status__in=(
            self.model.STATUS_NEW, self.model.STATUS_INPROGRESS
        ))

    # CHERRY ON THE TOP
    # define your permission code on an object here, the list view will call this
    # method prior to showing the menu item for the object:
    # in a list of objects with mixed statuses, each will have different menuitems
    # without hitting the db at all, check it out, the link component will call
    #      MRSRequestRejectView.clone(request=self.request, object=self.object).has_perm()
    # ZERO db hit, what a 1333337 trick
    def has_perm(self):
        if super().has_perm():
            return self.object.status in (
                self.model.STATUS_NEW,
                self.model.STATUS_INPROGRESS
            )
```

# 1337 Conclusion

h4x0|2z out there on the wild internet will just go down the rabbit hole of refactoring their code built on bare Django, just like Django itself was done, and just like then: it gives a framework on top of Django that gives you generic secure-by-default and working-by-default CRUD frontend, such as Iommi, CRUDLFA+, and *many* others even django-smartviews.

Keep up the gr8 work TriOptima !!!! Love it !!!!

:tophat:

**Comment by boxed** [comment]
You can do that with iommi now I think:

```python
class MyPage(Page):
    foo = Header('title')
    body = 'body text'
    table = Table(auto__model=User)

urlpatterns = [
    path('', MyPage().as_view()),    
]
```

Here's that code runnable: https://repl.it/@kankyo/iommi-replit-10#mysite/urls.py
(You should add another problem with django: it hides errors a LOT by default, this is imo much worse than the points you outline.)

**Comment by jpic** [comment]
I'm not saying that Django is perfect besides those points, but those points make me feel like Django is an unfinished framework, which Iommi solves elegantly ;)

If you are interested, I could extract the MVC part from crudlfap into a new django-mvc app, because really this pattern is great to build a CRUD on top of.

**Comment by boxed** [comment]
I will definitely take a look at crudlfap and see how it relates to iommi and if we can steal some good ideas :)

**Comment by jpic** [comment]
Sorry I'm a newb with Iommi, just found out about the admin CRUD, I think you could try much more easily if you make another Admin class, ie. Controller for example, that returns model.objects.none() by default for users who don't have the read permission, so that it's secure by default for non-admins.

Can it generate a default object-level menu in the Table ? Ie. by default with all permissions it should have like "detail", "edit", "delete". The trick to check permissions is to iterate over the views in the Controller and instanciate them with a given object (of the row) and the same request object to call has_perm, then some users might have that permission on some objects but not others.

If Iommi can do this then CRUDLFA+ won't be necessary because it really boils down to that + some features I needed along the way to keep my codebases DRY which you'd rather tailor to your own projects ;)

**Comment by boxed** [comment]
I believe we can do this popup menu in iommi. Basically you can just `get_absolute_url` on the object and append `/edit/`, `/view/`, `/delete/` on it and you get the URLs to put in that popup.
